### PR TITLE
Upgrading Django To Version 1.9 

### PR DESCRIPTION
**Pull request by Curious72**
#28

### CODE REVIEW

**Comment by deshraj** [comment]
@Curious72 I think simple upgrading django to 1.9 will not work here. Can you clone cloudcv on your local machine and check for the compatibility of other packages with django 1.9. I am sure you will get deprecation warnings on console.

**Comment by Curious72** [comment]
@DESHRAJ Yeah i am on it !

**Comment by deshraj** [comment]
@Curious72 are you still working on this ?

**Comment by deshraj** [comment]
Fixed in #38

**Pull request closed without merging**
