### PR TITLE
Code refactored according to PEP8 style

### PR DESCRIPTION
**Pull request by deshraj**

### CODE REVIEW

**Comment by deshraj** [comment]
@dexter1691 please review.

**Comment by abhshkdz** [comment]
@DESHRAJ I know I'm nitpicking but it might be a good idea to run [pep8](https://pypi.python.org/pypi/pep8) against the source. Output of `pep8 --statistics -qq app/*` (how often each error was found):

```
38      E101 indentation contains mixed spaces and tabs
2       E111 indentation is not a multiple of four
7       E114 indentation is not a multiple of four (comment)
9       E115 expected an indented block (comment)
8       E116 unexpected indentation (comment)
2       E127 continuation line over-indented for visual indent
21      E128 continuation line under-indented for visual indent
2       E202 whitespace before ']'
6       E203 whitespace before ','
3       E222 multiple spaces after operator
98      E225 missing whitespace around operator
129     E231 missing whitespace after ':'
86      E251 unexpected spaces around keyword / parameter equals
3       E261 at least two spaces before inline comment
2       E262 inline comment should start with '# '
56      E265 block comment should start with '# '
5       E266 too many leading '#' for block comment
1       E271 multiple spaces after keyword
2       E301 expected 1 blank line, found 0
15      E302 expected 2 blank lines, found 1
18      E303 too many blank lines (2)
3       E401 multiple imports on one line
136     E402 module level import not at top of file
302     E501 line too long (95 > 79 characters)
7       E701 multiple statements on one line (colon)
8       E703 statement ends with a semicolon
3       E711 comparison to None should be 'if cond is None:'
443     W191 indentation contains tabs
94      W291 trailing whitespace
7       W292 no newline at end of file
57      W293 blank line contains whitespace
4       W391 blank line at end of file
4       W503 line break before binary operator
2       W601 .has_key() is deprecated, use 'in'
```

`pep8 --show-source --show-pep8 app/*` will give you detailed line-by-line checks. Not that all need to be fixed, but it might be useful to keep in mind going forward.

**Comment by deshraj** [comment]
@abhshkdz Got your point. :+1: Will fix it. Also I was thinking to use flake8 after writing the test cases in travis CI build so that it will automatically check for the pep8 styling.

**Comment by abhshkdz** [comment]
That'd be great! :+1:

**Pull request merged**
