### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by NightFury13**
The updates README.rst file with the additions of Caffe-interface in the documentation.

@dexter1691 : I am submitting only the merge request to avoid any unnecessary conflicts. Please review.

### CODE REVIEW

**Comment by NightFury13** [comment]
You can view the Documentaiton here : http://nightfury13.github.io/CloudCV_Server/

**Comment by dexter1691** [comment]
The image files are not viewable.
And I am not able to merge this pull request automatically. Can you fix both of this?

**Comment by NightFury13** [comment]
> The images would be viewable once the code is merged as the files sources
have given according to the master repo.
> Also, I am not really sure what was wrong with the original gh-pages
branch on CloudCV_Server. When trying to rebuild the html pages, it threw
an error stating that it was unable to find the 'sphinx_rtd_theme' template
while the template provided in the /docs/source/conf.py was 'sphinxdoc', so
I dont really understand why are the makefiles looking for the
'sphinx_rtd_theme'
template.We might have to take a deeper look into this issue.

-Mohit

**Comment by NightFury13** [comment]
> The images would be viewable once the code is merged as the files sources have given according to the master repo.
> Also, I am not really sure what was wrong with the original gh-pages branch on CloudCV_Server. When trying to rebuild the html pages, it threw an error stating that it was unable to find the 'sphinx_rtd_theme' template while the template provided in the /docs/source/conf.py was 'sphinxdoc', so I dont really understand why are the makefiles looking for the 'sphinx_rtd_theme' template.We might have to take a deeper look into this issue.

**Comment by dexter1691** [comment]
I cannot merge them automatically? Why don't you pull all the changes from the batra-mlp-lab:gh-pages branch and merge it locally resolving all the conflicts. And then I will able to merge it without any fuss? 

Let me know if I am mistaken for some reason. Also, I am not sure why should you have images in the master branch? The git uses gh-pages branch to render the HTML, so we will actually never merge it with gh-pages. So the image URLs should get displayed. 

@DESHRAJ : I am right about the gh-pages right?

**Comment by deshraj** [comment]
@dexter1691 : Yeah you are right. Actually, images are missing in the _static directory in gh-pages branch. @NightFury13 : you need to add the images in that directory. 

Note: The static files for the sphinx resides in _static directory in gh-pages branch and not static directory of master branch.

**Comment by NightFury13** [comment]
I'll fix the issues locally and then send you a pull request again.

-Mohit

**Pull request closed without merging**
